apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkforeinok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkforeinok
  template:
    metadata:
      labels:
        app: dkforeinok
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: dkforeinok
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c91c278f-1cac-4f6e-9bf8-1859345dab13"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "c91c278f-1cac-4f6e-9bf8-1859345dab13"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
